export const cacheTags = {
  PAGINATED_TRANSACTIONS: "PAGINATED_TRANSACTIONS",
  PAGINATED_CATEGORIES: "PAGINATED_CATEGORIES",
  PAGINATED_BUDGETS: "PAGINATED_BUDGETS",
  PAGINATED_INCOMES: "PAGINATED_INCOMES",
  PAGINATED_BUDGETS_WITH_TRANSACTIONS: "PAGINATED_BUDGETS_WITH_TRANSACTIONS",
  PAGINATED_INCOMES_WITH_TRANSACTIONS: "PAGINATED_INCOMES_WITH_TRANSACTIONS",
  BUDGETS_SUMMARY: "BUDGETS_SUMMARY",
  INCOMES_SUMMARY: "INCOMES_SUMMARY",
  PAGINATED_POTS: "PAGINATED_POTS",
  PAGINATED_POTS_WITH_TRANSACTIONS: "PAGINATED_POTS_WITH_TRANSACTIONS",
  POTS_SUMMARY: "POTS_SUMMARY",
} as const;
