name: CI — Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
      NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
      NEXT_PUBLIC_IS_USING_EMULATORS: ${{ secrets.NEXT_PUBLIC_IS_USING_EMULATORS }}
      NEXT_PUBLIC_EMULATOR_HOST: ${{ secrets.NEXT_PUBLIC_EMULATOR_HOST }}
      NEXT_PUBLIC_FIRESTORE_EMULATOR_PORT: ${{ secrets.NEXT_PUBLIC_FIRESTORE_EMULATOR_PORT }}
      NEXT_PUBLIC_STORAGE_EMULATOR_PORT: ${{ secrets.NEXT_PUBLIC_STORAGE_EMULATOR_PORT }}
      NEXT_PUBLIC_FUNCTIONS_EMULATOR_PORT: ${{ secrets.NEXT_PUBLIC_FUNCTIONS_EMULATOR_PORT }}
      NEXT_PUBLIC_AUTH_EMULATOR_HOST: ${{ secrets.NEXT_PUBLIC_AUTH_EMULATOR_HOST }}
      NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
    strategy:
      matrix:
        node-version: [22]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies (Yarn Classic)
        run: yarn install --frozen-lockfile

      # Note: Playwright installation commented out since we're only running unit tests
      # Uncomment if you enable Storybook tests in vitest.config.ts
      # - name: Install Playwright browsers and OS deps
      #   run: yarn playwright install --with-deps

      - name: Run unit tests (Yarn)
        env:
          CI: true
        run: yarn run test:ci

      - name: Upload coverage on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/
